# Generated by Django 3.0.8 on 2020-08-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200117_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Roll_No',
            field=models.IntegerField(default='1'),
        ),
    ]
